### PR TITLE
Use Go modules

### PR DESCRIPTION
**Pull request by mrkanister**
Convert the current Godeps configuration to Go modules:

  go mod init
  go mod vendor

Fixes: laurent22/massren#42

### CODE REVIEW

**Comment by deepnum** [comment]
There is no need to run `go mod vendo`

**Comment by mrkanister** [comment]
While it's true that modules don't require the `vendor` folder and it's also my personal preference not to use it, there are valid reasons for a project to follow that approach. I didn't want to challenge it in this pull request to keep the change as small as possible.

**Comment by mrkanister** [comment]
The last push updates the module path from just `massren` to `github.com/laurent22/massren` because `go mod init` was not able to guess the full module path.

**Comment by mrkanister** [comment]
I am guessing the project is stale at the moment, so I am gonna close this for now.

**Pull request closed without merging**
